title: PACE Academy Student Handbook
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-sp-student-handbook
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics:  #----> Optional, Google analytics ID

fast_build: false
offline: false
preload_pages: true

styling_options:
  primary_brand_color: '#000080'  #----> Optional, theme color
  logo_path: /assets/sp3.jpg  #----> Optional, path to logo
  opendoc_logo_path: /assets/sp3.jpg
  feedback_url: https://form.gov.sg/5e744fb8b74872001193fe6a #----> Optional, feedback url

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

folders:
  - name: '/'
    title: 'PACE Academy Student Handbook'
    subtitle: ''
    order:
      - 'Documentinformation.md'
      - 'MessageDir.md'
      - 'AboutPACE.md'
      - 'ContactUs.md'
      - 'NavigationAroundSP.md'
      - 'GenStudentMatters.md'
      - 'GenCourseMatters.md'
      - 'SemestralExam.md'
      - 'CodeofConduct.md'
      - 'Disciplinary.md'
      - 'DNCPDPA.md'
      - 'CompResources.md'
      - 'SocialMedia.md'
      - 'IPCopyrightPlagiarism.md'
